-- ORBIS GESTÃO — CRM e suporte da ER Creative.
-- Execute após 015_subscriptions_and_retention.sql.

create table if not exists public.crm_leads (
  id uuid primary key default gen_random_uuid(), name text not null, company_name text,
  email text, phone text, status text not null default 'new' check(status in ('new','contacted','proposal','won','lost')),
  estimated_value numeric(12,2) not null default 0, next_contact_at timestamptz, notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(), ticket_number bigint generated by default as identity,
  company_id uuid references public.companies(id) on delete set null, title text not null, description text,
  contact_name text, contact_email text, priority text not null default 'normal' check(priority in ('low','normal','high','urgent')),
  status text not null default 'open' check(status in ('open','in_progress','waiting','resolved','closed')),
  due_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table if not exists public.crm_tasks (
  id uuid primary key default gen_random_uuid(), company_id uuid references public.companies(id) on delete set null,
  title text not null, description text, due_at timestamptz,
  priority text not null default 'normal' check(priority in ('low','normal','high','urgent')),
  status text not null default 'pending' check(status in ('pending','in_progress','completed','cancelled')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table if not exists public.knowledge_articles (
  id uuid primary key default gen_random_uuid(), title text not null, category text, content text not null,
  active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz
);
create table if not exists public.company_notes (
  id uuid primary key default gen_random_uuid(), company_id uuid not null references public.companies(id) on delete cascade,
  note text not null, created_by uuid references auth.users(id), created_at timestamptz not null default now(), deleted_at timestamptz
);

alter table public.crm_leads enable row level security;
alter table public.support_tickets enable row level security;
alter table public.crm_tasks enable row level security;
alter table public.knowledge_articles enable row level security;
alter table public.company_notes enable row level security;

do $$ declare t text; begin
  foreach t in array array['crm_leads','support_tickets','crm_tasks','knowledge_articles','company_notes'] loop
    execute format('drop policy if exists platform_full_access on public.%I',t);
    execute format('create policy platform_full_access on public.%I for all to authenticated using (public.is_platform_admin()) with check (public.is_platform_admin())',t);
  end loop;
end $$;

create or replace function public.platform_create_company(p_name text,p_slug text,p_document text,p_email text,p_phone text,p_address text,p_plan_code text default 'essencial')
returns uuid language plpgsql security definer set search_path=public as $$
declare cid uuid;
begin
  if not public.is_platform_admin() then raise exception 'Acesso exclusivo da ER Creative.'; end if;
  if nullif(trim(p_name),'') is null then raise exception 'Informe o nome da empresa.'; end if;
  insert into public.companies(name,slug,document,email,phone,address,active)
  values(trim(p_name),nullif(lower(trim(p_slug)),''),nullif(trim(p_document),''),nullif(trim(p_email),''),nullif(trim(p_phone),''),nullif(trim(p_address),''),true)
  returning id into cid;
  insert into public.company_subscriptions(company_id,plan_code,status,current_period_end) values(cid,coalesce(nullif(p_plan_code,''),'essencial'),'trial',current_date+30);
  return cid;
end $$;

create or replace function public.platform_update_company(p_company_id uuid,p_name text,p_slug text,p_document text,p_email text,p_phone text,p_address text,p_active boolean)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_platform_admin() then raise exception 'Acesso exclusivo da ER Creative.'; end if;
  update public.companies set name=trim(p_name),slug=nullif(lower(trim(p_slug)),''),document=nullif(trim(p_document),''),email=nullif(trim(p_email),''),phone=nullif(trim(p_phone),''),address=nullif(trim(p_address),''),active=coalesce(p_active,true),updated_at=now() where id=p_company_id;
  if not found then raise exception 'Empresa não encontrada.'; end if;
end $$;

create or replace function public.platform_get_company(p_company_id uuid)
returns jsonb language plpgsql stable security definer set search_path=public as $$
declare result jsonb;
begin
  if not public.is_platform_admin() then raise exception 'Acesso exclusivo da ER Creative.'; end if;
  select to_jsonb(c) into result from public.companies c where c.id=p_company_id;
  return result;
end $$;

grant select,insert,update,delete on public.crm_leads,public.support_tickets,public.crm_tasks,public.knowledge_articles,public.company_notes to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant execute on function public.platform_create_company(text,text,text,text,text,text,text) to authenticated;
grant execute on function public.platform_update_company(uuid,text,text,text,text,text,text,boolean) to authenticated;
grant execute on function public.platform_get_company(uuid) to authenticated;

create or replace function public.get_orbis_system_status()
returns jsonb language sql stable security definer set search_path=public as $$
select jsonb_build_object('database_version',16,'checked_at',now(),'tables_ok',to_regclass('public.crm_leads') is not null and to_regclass('public.support_tickets') is not null and to_regclass('public.crm_tasks') is not null and to_regclass('public.knowledge_articles') is not null,'functions_ok',to_regprocedure('public.platform_create_company(text,text,text,text,text,text,text)') is not null and to_regprocedure('public.remove_employee(uuid)') is not null,'storage_ok',exists(select 1 from storage.buckets where id='company-logos') and exists(select 1 from storage.buckets where id='service-order-proofs'))
$$;
