"use client";
import {useEffect,useMemo,useState} from "react";
import {RefreshCw,Search} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {AuthSession,Company,getEmployees,UserProfile} from "@/lib/supabase-auth";
import {AuditLog,getAuditLogs} from "@/lib/audit";
const names:Record<string,string>={"stock.movement":"Movimentação de estoque","product.deleted":"Produto excluído","product.deactivated":"Produto desativado","company.updated":"Empresa atualizada","company.created":"Empresa criada","service_order.accept":"OS aceita","service_order.start":"OS iniciada","service_order.finish":"OS finalizada","business_contacts.insert":"Cliente ou fornecedor cadastrado","business_contacts.update":"Cliente ou fornecedor atualizado","business_contacts.delete":"Cliente ou fornecedor excluído","categories.insert":"Categoria cadastrada","categories.update":"Categoria atualizada","categories.delete":"Categoria excluída","employee_invites.insert":"Convite de funcionário criado","employee_invites.update":"Convite de funcionário atualizado","profiles.update":"Funcionário atualizado"};
const entityNames:Record<string,string>={products:"Produto",companies:"Empresa",service_orders:"Ordem de serviço",business_contacts:"Cliente ou fornecedor",categories:"Categoria",employee_invites:"Convite",profiles:"Funcionário"};
export function AuditView({session,company}:{session:AuthSession;company:Company}){
 const[logs,setLogs]=useState<AuditLog[]>([]),[employees,setEmployees]=useState<UserProfile[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[selected,setSelected]=useState<AuditLog|null>(null);
 const load=async()=>{setLoading(true);setError("");try{const[l,e]=await Promise.all([getAuditLogs(session,company.id),getEmployees(session,company.id)]);setLogs(l);setEmployees(e)}catch(err){setError(err instanceof Error?err.message:"Não foi possível carregar o histórico.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[company.id,session.access_token]);
 const user=(id:string|null)=>employees.find(item=>item.id===id)?.full_name||"Usuário do sistema";
 const filtered=useMemo(()=>logs.filter(log=>`${names[log.action]||log.action} ${entityNames[log.entity]||log.entity} ${user(log.user_id)}`.toLowerCase().includes(query.toLowerCase())),[logs,employees,query]);
 return <><div className="page-head"><div><h2>Histórico de atividades</h2><p>Registros de segurança e alterações realizadas no sistema.</p></div><Button variant="outline" onClick={load} disabled={loading}><RefreshCw/>Atualizar</Button></div>{error&&<div className="auth-message error-message">{error}</div>}<section className="panel table-panel"><div className="table-tools"><div className="search"><Search/><Input placeholder="Buscar atividade ou usuário" value={query} onChange={event=>setQuery(event.target.value)}/></div></div><div className="table-scroll"><table><thead><tr><th>Data e hora</th><th>Usuário</th><th>Atividade</th><th>Registro</th><th>Detalhes</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Carregando histórico…</td></tr>:filtered.length===0?<tr><td colSpan={5}>Nenhuma atividade encontrada.</td></tr>:filtered.map(log=><tr key={log.id}><td>{new Date(log.created_at).toLocaleString("pt-BR")}</td><td>{user(log.user_id)}</td><td><strong>{names[log.action]||log.action}</strong></td><td>{entityNames[log.entity]||log.entity}</td><td><Button size="sm" variant="ghost" onClick={()=>setSelected(log)}>Visualizar</Button></td></tr>)}</tbody></table></div></section><Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="modal"><DialogHeader><DialogTitle>{selected&&(names[selected.action]||selected.action)}</DialogTitle><DialogDescription>{selected&&`${new Date(selected.created_at).toLocaleString("pt-BR")} · ${user(selected.user_id)}`}</DialogDescription></DialogHeader>{selected&&<div className="audit-detail"><p><strong>Tipo de registro:</strong> {entityNames[selected.entity]||selected.entity}</p><p><strong>Identificador:</strong> {selected.entity_id||"—"}</p>{selected.old_data&&<><strong>Dados anteriores</strong><pre>{JSON.stringify(selected.old_data,null,2)}</pre></>}{selected.new_data&&<><strong>Dados registrados</strong><pre>{JSON.stringify(selected.new_data,null,2)}</pre></>}</div>}</DialogContent></Dialog></>;
}
