"use client";
import {useEffect,useMemo,useState} from "react";
import {BarChart3,CheckCircle2,Clock3,Download,DollarSign} from "lucide-react";
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {Button} from "@/components/ui/button";
import {AuthSession,Company} from "@/lib/supabase-auth";
import {ServiceOrder,getServiceOrders} from "@/lib/service-orders";
type Period="month"|"quarter"|"semester"|"year";
const names:Record<Period,string>={month:"Mês atual",quarter:"Trimestre",semester:"Semestre",year:"Ano"};
const money=(v:number)=>Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function startOf(p:Period){const n=new Date();if(p==="month")return new Date(n.getFullYear(),n.getMonth(),1);if(p==="quarter")return new Date(n.getFullYear(),Math.floor(n.getMonth()/3)*3,1);if(p==="semester")return new Date(n.getFullYear(),n.getMonth()<6?0:6,1);return new Date(n.getFullYear(),0,1)}
export function BillingView({session,company}:{session:AuthSession;company:Company}){
 const [orders,setOrders]=useState<ServiceOrder[]>([]),[period,setPeriod]=useState<Period>("month"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{setLoading(true);getServiceOrders(session,company.id).then(setOrders).catch(e=>setError(e instanceof Error?e.message:"Erro ao carregar o faturamento.")).finally(()=>setLoading(false))},[session,company.id]);
 const periodOrders=useMemo(()=>{const start=startOf(period).getTime();return orders.filter(o=>new Date(o.completed_at||o.created_at).getTime()>=start)},[orders,period]);
 const completed=periodOrders.filter(o=>o.status==="completed"),pending=periodOrders.filter(o=>!["completed","cancelled"].includes(o.status));
 const billed=completed.reduce((s,o)=>s+Number(o.value),0),pendingValue=pending.reduce((s,o)=>s+Number(o.value),0),average=completed.length?billed/completed.length:0;
 const chart=useMemo(()=>{const fmt=new Intl.DateTimeFormat("pt-BR",{month:"short"}),count=period==="year"?12:period==="semester"?6:period==="quarter"?3:1,now=new Date();return Array.from({length:count},(_,i)=>{const d=new Date(now.getFullYear(),now.getMonth()-(count-1-i),1);const revenue=orders.filter(o=>{if(o.status!=="completed"||!o.completed_at)return false;const c=new Date(o.completed_at);return c.getFullYear()===d.getFullYear()&&c.getMonth()===d.getMonth()}).reduce((s,o)=>s+Number(o.value),0);return{month:fmt.format(d).replace(".",""),revenue}})},[orders,period]);
 const exportCsv=()=>{const rows=[["OS","Cliente","Serviço","Status","Valor","Finalizada em"],...periodOrders.map(o=>["OS-"+String(o.order_number).padStart(5,"0"),o.customer?.name||"",o.title,o.status,Number(o.value).toFixed(2).replace(".",","),o.completed_at?new Date(o.completed_at).toLocaleString("pt-BR"):""])];const csv=rows.map(r=>r.map(c=>'"'+String(c).replaceAll('"','""')+'"').join(";")).join("\n");const url=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=url;a.download="faturamento-"+period+"-"+new Date().toISOString().slice(0,10)+".csv";a.click();URL.revokeObjectURL(url)};
 return <><div className="page-head"><div><h2>Faturamento</h2><p>Valores reais calculados pelas ordens de serviço.</p></div><div className="actions billing-actions"><select value={period} onChange={e=>setPeriod(e.target.value as Period)}>{Object.entries(names).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><Button variant="outline" onClick={exportCsv} disabled={loading||!periodOrders.length}><Download/>Exportar</Button></div></div>{error&&<div className="auth-message error-message">{error}</div>}<div className="mini-metrics billing-metrics"><Metric icon={DollarSign} label="Faturamento realizado" value={loading?"…":money(billed)}/><Metric icon={CheckCircle2} label="Serviços finalizados" value={loading?"…":String(completed.length)}/><Metric icon={Clock3} label="Valores pendentes" value={loading?"…":money(pendingValue)}/><Metric icon={BarChart3} label="Ticket médio" value={loading?"…":money(average)}/></div><section className="panel chart-panel tall"><div className="panel-head"><div><h3>Evolução do faturamento</h3><p>Somente ordens finalizadas no período.</p></div></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis tickFormatter={v=>String(v/1000)+"k"}/><Tooltip formatter={v=>money(Number(v))}/><Area type="monotone" dataKey="revenue" name="Faturamento" stroke="#2457d6" fill="#2457d622" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></section><section className="panel table-panel billing-table"><div className="panel-head"><div><h3>Ordens do período</h3><p>{periodOrders.length} registros encontrados.</p></div></div><div className="table-scroll"><table><thead><tr><th>Ordem</th><th>Cliente / serviço</th><th>Situação</th><th>Valor</th><th>Conclusão</th></tr></thead><tbody>{!periodOrders.length?<tr><td colSpan={5}>Nenhuma ordem neste período.</td></tr>:periodOrders.map(o=><tr key={o.id}><td><strong className="order-id">OS-{String(o.order_number).padStart(5,"0")}</strong></td><td><div className="two-lines"><strong>{o.customer?.name||"Cliente"}</strong><span>{o.title}</span></div></td><td><span className={"status "+(o.status==="completed"?"success":o.status==="cancelled"?"danger-bg":"warning")}>{o.status==="completed"?"Finalizada":o.status==="cancelled"?"Cancelada":"Pendente"}</span></td><td><strong>{money(o.value)}</strong></td><td>{o.completed_at?new Date(o.completed_at).toLocaleDateString("pt-BR"):"—"}</td></tr>)}</tbody></table></div></section></>;
}
function Metric({icon:Icon,label,value}:{icon:typeof DollarSign;label:string;value:string}){return <div><Icon/><span><small>{label}</small><strong>{value}</strong></span></div>}
