"use client";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Boxes, ClipboardList, DollarSign, Package, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AuthSession, Company } from "@/lib/supabase-auth";
import { getProducts, Product } from "@/lib/inventory";
import { getServiceOrders, ServiceOrder } from "@/lib/service-orders";
type View="dashboard"|"stock"|"orders"|"customers"|"suppliers"|"employees"|"billing"|"reports"|"settings";
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const statusName:Record<ServiceOrder["status"],string>={waiting:"Aguardando funcionário",accepted:"Aceita",in_progress:"Em andamento",completed:"Finalizada",cancelled:"Cancelada"};
export function DashboardView({role,userName,session,company,setView}:{role:"admin"|"employee";userName:string;session:AuthSession;company:Company;setView:(v:View)=>void}){
 const [products,setProducts]=useState<Product[]>([]),[orders,setOrders]=useState<ServiceOrder[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{const[p,o]=await Promise.all([getProducts(session,company.id),getServiceOrders(session,company.id)]);setProducts(p);setOrders(o)}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar o painel.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[session,company.id]);
 const data=useMemo(()=>{const low=products.filter(p=>Number(p.quantity)<=Number(p.min_stock)).sort((a,b)=>Number(a.quantity)-Number(b.quantity));const open=orders.filter(o=>o.status!=="completed"&&o.status!=="cancelled");const now=new Date();const revenue=orders.filter(o=>o.status==="completed"&&o.completed_at&&new Date(o.completed_at).getMonth()===now.getMonth()&&new Date(o.completed_at).getFullYear()===now.getFullYear()).reduce((s,o)=>s+Number(o.value||0),0);return{low,open,stockValue:products.reduce((s,p)=>s+Number(p.quantity)*Number(p.cost_price),0),revenue}},[products,orders]);
 return <><div className="page-head"><div><h2>Olá, {userName.trim().split(" ")[0]||"Usuário"}!</h2><p>Acompanhe os números reais da operação de {company.name}.</p></div><Button variant="outline" onClick={load} disabled={loading}><RefreshCw/>Atualizar</Button></div>{error&&<div className="auth-message error-message">{error}</div>}<div className="metric-grid"><Metric label="Produtos ativos" value={loading?"—":String(products.length)} note="Itens cadastrados" icon={Boxes} tone="blue"/><Metric label="Estoque baixo" value={loading?"—":String(data.low.length)} note={data.low.length?"Requer atenção":"Estoque saudável"} icon={AlertTriangle} tone="orange"/><Metric label="Ordens abertas" value={loading?"—":String(data.open.length)} note="Em atendimento ou aguardando" icon={ClipboardList} tone="purple"/>{role==="admin"?<Metric label="Faturamento do mês" value={loading?"—":money(data.revenue)} note={`Valor em estoque: ${money(data.stockValue)}`} icon={DollarSign} tone="green"/>:<Metric label="Ordens finalizadas" value={loading?"—":String(orders.filter(o=>o.status==="completed").length)} note="Total registrado" icon={Package} tone="green"/>}</div><div className="dashboard-grid"><section className="panel table-panel"><div className="panel-head dashboard-panel-head"><div><h3>Ordens de serviço recentes</h3><p>Últimos serviços cadastrados</p></div><button onClick={()=>setView("orders")}>Ver todas</button></div><div className="table-scroll"><table><thead><tr><th>Ordem</th><th>Cliente / serviço</th><th>Status</th><th>Valor</th></tr></thead><tbody>{loading?<tr><td colSpan={4}>Carregando…</td></tr>:orders.length===0?<tr><td colSpan={4}>Nenhuma ordem cadastrada.</td></tr>:orders.slice(0,5).map(o=><tr key={o.id} className="clickable-row" onClick={()=>setView("orders")}><td><strong className="order-id">OS-{String(o.order_number).padStart(4,"0")}</strong></td><td className="two-lines"><strong>{o.customer?.name||"Cliente"}</strong><span>{o.title}</span></td><td><span className={`status ${o.status==="completed"?"success":o.status==="in_progress"?"info":o.status==="cancelled"?"danger-bg":"warning"}`}>{statusName[o.status]}</span></td><td>{role==="admin"?money(Number(o.value||0)):"—"}</td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-head"><div><h3>Atenção no estoque</h3><p>Produtos no mínimo ou abaixo dele</p></div><button onClick={()=>setView("stock")}>Ver estoque</button></div><div className="attention">{loading?<p>Carregando…</p>:data.low.length===0?<p className="dashboard-empty">Nenhum produto com estoque baixo.</p>:data.low.slice(0,5).map(p=><div key={p.id} className={Number(p.quantity)===0?"danger":"warn"}><span className="square"><Package/></span><span><strong>{p.name}</strong><small>{p.sku} • mínimo {Number(p.min_stock)}</small></span><span><strong>{Number(p.quantity)}</strong><small>{p.unit}</small></span></div>)}</div></section></div></>;
}
function Metric({label,value,note,icon:Icon,tone}:{label:string;value:string;note:string;icon:typeof Boxes;tone:string}){return <article className="metric-card"><span>{label}</span><strong>{value}</strong><small>{note}</small><i className={`metric-icon ${tone}`}><Icon/></i></article>}
