"use client";
import {useEffect,useMemo,useState} from "react";
import {Building2,Download,Mail,MapPin,Pencil,Phone,Plus,Search,Trash2,UserRound} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {AuthSession,Company} from "@/lib/supabase-auth";
import {BusinessContact,ContactType,createBusinessContact,getBusinessContacts,updateBusinessContact} from "@/lib/business-contacts";
import {downloadCsv} from "@/lib/csv";

const blank={person_type:"company" as "person"|"company",name:"",trade_name:"",document:"",contact_name:"",phone:"",email:"",postal_code:"",address:"",address_number:"",complement:"",neighborhood:"",city:"",state:"",notes:""};
export function DirectoryView({type,role,session,company,flash}:{type:ContactType;role:"admin"|"employee";session:AuthSession;company:Company;flash:(s:string)=>void}){
 const customer=type==="customer",title=customer?"Clientes":"Fornecedores";
 const [rows,setRows]=useState<BusinessContact[]>([]),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[lookingCep,setLookingCep]=useState(false),[cepMessage,setCepMessage]=useState(""),[editing,setEditing]=useState<BusinessContact|null>(null),[details,setDetails]=useState<BusinessContact|null>(null),[form,setForm]=useState(blank);
 const load=async()=>{setLoading(true);setError("");try{setRows(await getBusinessContacts(session,company.id,type))}catch(e){setError(e instanceof Error?e.message:`Erro ao carregar ${title.toLowerCase()}.`)}finally{setLoading(false)}};
 useEffect(()=>{load()},[company.id,type]);
 const filtered=useMemo(()=>rows.filter(r=>`${r.name} ${r.trade_name||""} ${r.document||""} ${r.phone||""} ${r.email||""}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
 const openNew=()=>{setEditing(null);setForm(blank);setError("");setCepMessage("");setOpen(true)};
 const openEdit=(r:BusinessContact)=>{setEditing(r);setForm({person_type:r.person_type,name:r.name,trade_name:r.trade_name||"",document:r.document||"",contact_name:r.contact_name||"",phone:r.phone||"",email:r.email||"",postal_code:r.postal_code||"",address:r.address||"",address_number:r.address_number||"",complement:r.complement||"",neighborhood:r.neighborhood||"",city:r.city||"",state:r.state||"",notes:r.notes||""});setError("");setCepMessage("");setOpen(true)};
 const data=()=>({company_id:company.id,entity_type:type,...form,trade_name:form.trade_name||null,document:form.document||null,contact_name:form.contact_name||null,phone:form.phone||null,email:form.email||null,postal_code:form.postal_code||null,address:form.address||null,address_number:form.address_number||null,complement:form.complement||null,neighborhood:form.neighborhood||null,city:form.city||null,state:form.state.toUpperCase()||null,notes:form.notes||null});
 const changeCep=(value:string)=>{const digits=value.replace(/\D/g,"").slice(0,8);setCepMessage("");setForm(f=>({...f,postal_code:digits.length>5?`${digits.slice(0,5)}-${digits.slice(5)}`:digits}))};
 const lookupCep=async()=>{const cep=form.postal_code.replace(/\D/g,"");if(!cep)return;if(cep.length!==8){setCepMessage("Digite os 8 números do CEP.");return}setLookingCep(true);setCepMessage("");try{const response=await fetch(`https://viacep.com.br/ws/${cep}/json/`);if(!response.ok)throw new Error();const result=await response.json();if(result.erro){setCepMessage("CEP não encontrado.");return}setForm(f=>({...f,postal_code:result.cep||f.postal_code,address:result.logradouro||f.address,neighborhood:result.bairro||f.neighborhood,city:result.localidade||f.city,state:result.uf||f.state,complement:f.complement||result.complement||""}));setCepMessage("Endereço preenchido. Informe o número.")}catch{setCepMessage("Não foi possível consultar o CEP. Preencha o endereço manualmente.")}finally{setLookingCep(false)}};
 const save=async()=>{if(!form.name.trim())return setError("Informe o nome ou razão social.");setSaving(true);setError("");try{editing?await updateBusinessContact(session,editing.id,data()):await createBusinessContact(session,data());setOpen(false);await load();flash(`${customer?"Cliente":"Fornecedor"} ${editing?"atualizado":"cadastrado"} com sucesso.`)}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar cadastro.")}finally{setSaving(false)}};
 const remove=async(r:BusinessContact)=>{if(!confirm(`Excluir o cadastro de “${r.name}”?`))return;setSaving(true);try{await updateBusinessContact(session,r.id,{active:false});await load();flash(`${customer?"Cliente":"Fornecedor"} excluído da lista.`)}catch(e){setError(e instanceof Error?e.message:"Erro ao excluir cadastro.")}finally{setSaving(false)}};
 const exportRows=()=>downloadCsv(`${customer?"clientes":"fornecedores"}-${new Date().toISOString().slice(0,10)}.csv`,[["Nome / razão social","Nome fantasia","CPF / CNPJ","Contato","Telefone","E-mail","CEP","Endereço","Número","Bairro","Cidade","UF","Observações"],...filtered.map(r=>[r.name,r.trade_name,r.document,r.contact_name,r.phone,r.email,r.postal_code,r.address,r.address_number,r.neighborhood,r.city,r.state,r.notes])]);
 return <><div className="page-head"><div><h2>{title}</h2><p>{customer?"Cadastros e contatos para ordens de serviço.":"Fornecimento, contatos e dados comerciais."}</p></div>{role==="admin"&&<Button onClick={openNew}><Plus/>Novo cadastro</Button>}</div>{error&&<div className="auth-message error-message">{error}</div>}<section className="panel table-panel"><div className="table-tools"><div className="search"><Search/><Input placeholder={`Buscar ${title.toLowerCase()}`} value={query} onChange={e=>setQuery(e.target.value)}/></div><Button variant="outline" onClick={exportRows} disabled={!filtered.length}><Download/>Exportar</Button><span className="directory-count">{rows.length} ativos</span></div><div className="directory">{loading?<p className="empty-directory">Carregando…</p>:filtered.length===0?<p className="empty-directory">Nenhum cadastro encontrado.</p>:filtered.map(r=><article key={r.id} className="clickable-row" onClick={()=>setDetails(r)}><div className="square">{r.person_type==="person"?<UserRound/>:<Building2/>}</div><div><strong>{r.name}</strong><span>{r.document||r.trade_name||"Documento não informado"}</span></div><div><small>Contato</small><strong>{r.phone||"—"}</strong><span>{r.email||r.contact_name||""}</span></div><div><small>Localização</small><strong>{[r.city,r.state].filter(Boolean).join(" / ")||"—"}</strong></div>{role==="admin"?<div className="row-actions" onClick={e=>e.stopPropagation()}><Button variant="outline" size="icon" aria-label={`Editar ${r.name}`} onClick={()=>openEdit(r)}><Pencil/></Button><Button variant="outline" size="icon" aria-label={`Excluir ${r.name}`} onClick={()=>remove(r)} disabled={saving}><Trash2/></Button></div>:<span className="status neutral">Visualização</span>}</article>)}</div></section>
 <Dialog open={!!details} onOpenChange={v=>!v&&setDetails(null)}><DialogContent className="modal"><DialogHeader><DialogTitle>{details?.name}</DialogTitle><DialogDescription>Informações completas do cadastro.</DialogDescription></DialogHeader>{details&&<div className="detail-grid"><Detail label="Tipo" value={details.person_type==="company"?"Pessoa jurídica":"Pessoa física"}/><Detail label="Nome fantasia" value={details.trade_name}/><Detail label="CPF / CNPJ" value={details.document}/><Detail label="Pessoa de contato" value={details.contact_name}/><Detail label="Telefone / WhatsApp" value={details.phone}/><Detail label="E-mail" value={details.email}/><Detail label="CEP" value={details.postal_code}/><Detail label="Endereço" value={[details.address,details.address_number].filter(Boolean).join(", ")}/><Detail label="Complemento" value={details.complement}/><Detail label="Bairro" value={details.neighborhood}/><Detail label="Cidade / UF" value={[details.city,details.state].filter(Boolean).join(" / ")}/><Detail label="Observações" value={details.notes} wide/></div>}</DialogContent></Dialog>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="modal wide"><DialogHeader><DialogTitle>{editing?"Editar":"Novo"} {customer?"cliente":"fornecedor"}</DialogTitle><DialogDescription>Preencha os dados principais. Somente o nome é obrigatório.</DialogDescription></DialogHeader>{error&&<div className="auth-message error-message">{error}</div>}<div className="modal-form"><div className="form-grid"><label>Tipo<select value={form.person_type} onChange={e=>setForm(f=>({...f,person_type:e.target.value as "person"|"company"}))}><option value="company">Pessoa jurídica</option><option value="person">Pessoa física</option></select></label><Field label="Nome / razão social" value={form.name} set={v=>setForm(f=>({...f,name:v}))}/><Field label="Nome fantasia" value={form.trade_name} set={v=>setForm(f=>({...f,trade_name:v}))}/><Field label="CPF / CNPJ" value={form.document} set={v=>setForm(f=>({...f,document:v}))}/><Field label="Pessoa de contato" value={form.contact_name} set={v=>setForm(f=>({...f,contact_name:v}))}/><Field label="Telefone / WhatsApp" value={form.phone} set={v=>setForm(f=>({...f,phone:v}))}/><Field label="E-mail" type="email" value={form.email} set={v=>setForm(f=>({...f,email:v}))}/><label>CEP<Input inputMode="numeric" value={form.postal_code} onChange={e=>changeCep(e.target.value)} onBlur={lookupCep} placeholder="00000-000"/>{(lookingCep||cepMessage)&&<small className="cep-status">{lookingCep?"Consultando CEP…":cepMessage}</small>}</label><Field label="Endereço" value={form.address} set={v=>setForm(f=>({...f,address:v}))}/><Field label="Número" value={form.address_number} set={v=>setForm(f=>({...f,address_number:v}))}/><Field label="Complemento" value={form.complement} set={v=>setForm(f=>({...f,complement:v}))}/><Field label="Bairro" value={form.neighborhood} set={v=>setForm(f=>({...f,neighborhood:v}))}/><Field label="Cidade" value={form.city} set={v=>setForm(f=>({...f,city:v}))}/><Field label="UF" value={form.state} set={v=>setForm(f=>({...f,state:v.slice(0,2)}))}/></div><label>Observações<textarea value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/></label><Button onClick={save} disabled={saving}>{saving?"Salvando…":editing?"Salvar alterações":"Cadastrar"}</Button></div></DialogContent></Dialog></>;
}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label>{label}<Input type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function Detail({label,value,wide=false}:{label:string;value?:string|null;wide?:boolean}){return <div className={wide?"wide":""}><small>{label}</small><strong>{value||"Não informado"}</strong></div>}
