"use client";
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Archive, DollarSign, Download, History, Package, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { AuthSession,Company } from "@/lib/supabase-auth";
import { Category,Product,createCategory,createProduct,deleteProduct,getCategories,getMovements,getProducts,registerMovement,updateProduct } from "@/lib/inventory";
import { downloadCsv } from "@/lib/csv";

const money=(v:number)=>Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const emptyProduct={name:"",sku:"",barcode:"",category_id:"",unit:"UN",min_stock:"0",cost_price:"0",sale_price:"0",location:"",ncm:"",description:"",initial_quantity:"0"};

export function InventoryView({session,company,role,flash}:{session:AuthSession;company:Company;role:"admin"|"employee";flash:(s:string)=>void}){
 const [products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 const [productOpen,setProductOpen]=useState(false),[movementOpen,setMovementOpen]=useState(false),[historyOpen,setHistoryOpen]=useState(false);
 const [form,setForm]=useState(emptyProduct),[categoryName,setCategoryName]=useState(""),[saving,setSaving]=useState(false);
 const [editing,setEditing]=useState<Product|null>(null);
 const [movement,setMovement]=useState({product_id:"",type:role==="employee"?"exit":"entry",quantity:"1",reason:"",note_number:""});
 const [history,setHistory]=useState<any[]>([]);
 const [details,setDetails]=useState<Product|null>(null);
 const load=async()=>{setLoading(true);setError("");try{const [p,c]=await Promise.all([getProducts(session,company.id),getCategories(session,company.id)]);setProducts(p);setCategories(c)}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar estoque.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[company.id]);
 const filtered=products.filter(p=>`${p.name} ${p.sku} ${p.categories?.name||""}`.toLowerCase().includes(query.toLowerCase()));
 const totals=useMemo(()=>({cost:products.reduce((s,p)=>s+Number(p.quantity)*Number(p.cost_price),0),low:products.filter(p=>Number(p.quantity)<=Number(p.min_stock)).length,zero:products.filter(p=>Number(p.quantity)===0).length}),[products]);
 const productData={name:form.name.trim(),sku:form.sku.trim(),barcode:form.barcode||null,category_id:form.category_id||null,unit:form.unit,min_stock:Number(form.min_stock),cost_price:Number(form.cost_price),sale_price:Number(form.sale_price),location:form.location||null,ncm:form.ncm||null,description:form.description||null,image_url:null};
 const saveProduct=async()=>{if(!form.name.trim()||!form.sku.trim())return setError("Informe nome e código do produto.");setSaving(true);setError("");try{if(editing){await updateProduct(session,editing.id,productData);flash("Produto atualizado com sucesso.")}else{await createProduct(session,{company_id:company.id,...productData,initial_quantity:Number(form.initial_quantity)});flash("Produto cadastrado e estoque inicial registrado.")}setProductOpen(false);setEditing(null);setForm(emptyProduct);await load()}catch(e){setError(e instanceof Error?e.message:"Erro ao salvar produto.")}finally{setSaving(false)}};
 const openNew=()=>{setEditing(null);setForm(emptyProduct);setProductOpen(true)};
 const openEdit=(p:Product)=>{setEditing(p);setForm({name:p.name,sku:p.sku,barcode:p.barcode||"",category_id:p.category_id||"",unit:p.unit,min_stock:String(p.min_stock),cost_price:String(p.cost_price),sale_price:String(p.sale_price),location:p.location||"",ncm:p.ncm||"",description:p.description||"",initial_quantity:"0"});setProductOpen(true)};
 const removeProduct=async(p:Product)=>{if(!window.confirm(`Excluir o produto “${p.name}”? Se ele possuir movimentações, será desativado para preservar o histórico.`))return;setSaving(true);setError("");try{const result=await deleteProduct(session,p.id);await load();flash(result.mode==="deleted"?"Produto excluído.":"Produto desativado e histórico preservado.")}catch(e){setError(e instanceof Error?e.message:"Erro ao excluir produto.")}finally{setSaving(false)}};
 const addCategory=async()=>{if(!categoryName.trim())return;try{const c=await createCategory(session,company.id,categoryName);setCategories(v=>[...v,c].sort((a,b)=>a.name.localeCompare(b.name)));setForm(v=>({...v,category_id:c.id}));setCategoryName("");flash("Categoria criada.")}catch(e){setError(e instanceof Error?e.message:"Erro ao criar categoria.")}};
 const saveMovement=async()=>{if(!movement.product_id||!movement.reason.trim())return setError("Selecione o produto e informe o motivo.");setSaving(true);setError("");try{await registerMovement(session,{product_id:movement.product_id,type:movement.type,quantity:Number(movement.quantity),reason:movement.reason,note_number:movement.note_number});setMovementOpen(false);setMovement({product_id:"",type:role==="employee"?"exit":"entry",quantity:"1",reason:"",note_number:""});await load();flash("Movimentação registrada com saldo atualizado.")}catch(e){setError(e instanceof Error?e.message:"Erro na movimentação.")}finally{setSaving(false)}};
 const openHistory=async()=>{setHistoryOpen(true);try{setHistory(await getMovements(session,company.id))}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar histórico.")}};
 const exportStock=()=>downloadCsv(`estoque-${new Date().toISOString().slice(0,10)}.csv`,[["SKU","Produto","Categoria","Unidade","Quantidade","Estoque mínimo","Localização",...(role==="admin"?["Custo","Preço de venda","Valor em estoque"]:[])],...filtered.map(p=>[p.sku,p.name,p.categories?.name||"",p.unit,Number(p.quantity),Number(p.min_stock),p.location||"",...(role==="admin"?[Number(p.cost_price).toFixed(2),Number(p.sale_price).toFixed(2),(Number(p.quantity)*Number(p.cost_price)).toFixed(2)]:[])])]);
 return <><div className="page-head"><div><h2>Controle de estoque</h2><p>Produtos e movimentações gravados no banco de dados.</p></div><div className="actions"><Button variant="outline" onClick={openHistory}><History/>Histórico</Button>{role==="admin"&&<Button variant="outline" onClick={openNew}><Plus/>Novo produto</Button>}<Button onClick={()=>setMovementOpen(true)}><Plus/>Registrar {role==="admin"?"movimentação":"saída"}</Button></div></div>{error&&<div className="auth-message error-message">{error}</div>}<div className="mini-metrics"><Mini icon={Package} label="Produtos ativos" value={String(products.length)}/><Mini icon={AlertTriangle} label="Estoque baixo" value={String(totals.low)}/><Mini icon={Archive} label="Produtos zerados" value={String(totals.zero)}/>{role==="admin"&&<Mini icon={DollarSign} label="Valor em estoque" value={money(totals.cost)}/>}</div><section className="panel table-panel"><div className="table-tools"><div className="search"><Search/><Input placeholder="Buscar produto, SKU ou categoria" value={query} onChange={e=>setQuery(e.target.value)}/></div><Button variant="outline" onClick={exportStock} disabled={!filtered.length}><Download/>Exportar</Button></div><div className="table-scroll"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Local</th><th>Nível</th>{role==="admin"&&<><th>Custo</th><th>Valor</th></>}<th>Situação</th>{role==="admin"&&<th>Ações</th>}</tr></thead><tbody>{loading?<tr><td colSpan={8}>Carregando estoque…</td></tr>:filtered.length===0?<tr><td colSpan={8}>Nenhum produto cadastrado.</td></tr>:filtered.map(p=><tr key={p.id} className="clickable-row" onClick={()=>setDetails(p)}><td><div className="product"><div className="square"><Package/></div><span><strong>{p.name}</strong><small>{p.sku} • {p.unit}</small></span></div></td><td>{p.categories?.name||"Sem categoria"}</td><td>{p.location||"—"}</td><td><div className="level"><span><strong>{Number(p.quantity)}</strong> / mín. {Number(p.min_stock)}</span><Progress value={Math.min(Number(p.quantity)/Math.max(Number(p.min_stock)*2,1)*100,100)}/></div></td>{role==="admin"&&<><td>{money(Number(p.cost_price))}</td><td><strong>{money(Number(p.cost_price)*Number(p.quantity))}</strong></td></>}<td>{Number(p.quantity)===0?<span className="status danger-bg">Zerado</span>:Number(p.quantity)<=Number(p.min_stock)?<span className="status warning">Estoque baixo</span>:<span className="status success">Normal</span>}</td>{role==="admin"&&<td><div className="row-actions" onClick={e=>e.stopPropagation()}><Button variant="outline" size="icon" aria-label={`Editar ${p.name}`} onClick={()=>openEdit(p)}><Pencil/></Button><Button variant="outline" size="icon" aria-label={`Excluir ${p.name}`} onClick={()=>removeProduct(p)} disabled={saving}><Trash2/></Button></div></td>}</tr>)}</tbody></table></div></section>
 <Dialog open={!!details} onOpenChange={v=>!v&&setDetails(null)}><DialogContent className="modal"><DialogHeader><DialogTitle>{details?.name}</DialogTitle><DialogDescription>Informações completas do produto.</DialogDescription></DialogHeader>{details&&<div className="detail-grid"><Detail label="Código / SKU" value={details.sku}/><Detail label="Código de barras" value={details.barcode}/><Detail label="Categoria" value={details.categories?.name}/><Detail label="Unidade" value={details.unit}/><Detail label="Quantidade atual" value={`${Number(details.quantity)} ${details.unit}`}/><Detail label="Estoque mínimo" value={String(Number(details.min_stock))}/>{role==="admin"&&<><Detail label="Preço de custo" value={money(Number(details.cost_price))}/><Detail label="Preço de venda" value={money(Number(details.sale_price))}/><Detail label="Valor em estoque" value={money(Number(details.quantity)*Number(details.cost_price))}/></>}<Detail label="Localização" value={details.location}/><Detail label="NCM" value={details.ncm}/><Detail label="Descrição" value={details.description} wide/></div>}</DialogContent></Dialog>
 <Dialog open={productOpen} onOpenChange={setProductOpen}><DialogContent className="modal wide"><DialogHeader><DialogTitle>{editing?"Editar produto":"Novo produto"}</DialogTitle><DialogDescription>{editing?"Corrija os dados do produto. O saldo é alterado somente por movimentações.":"Cadastre o produto e seu saldo inicial."}</DialogDescription></DialogHeader><div className="modal-form"><div className="form-grid"><Field label="Nome" value={form.name} set={v=>setForm(f=>({...f,name:v}))}/><Field label="SKU / código" value={form.sku} set={v=>setForm(f=>({...f,sku:v}))}/><Field label="Código de barras" value={form.barcode} set={v=>setForm(f=>({...f,barcode:v}))}/><label>Categoria<select value={form.category_id} onChange={e=>setForm(f=>({...f,category_id:e.target.value}))}><option value="">Sem categoria</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Field label="Unidade" value={form.unit} set={v=>setForm(f=>({...f,unit:v}))}/><Field label="Localização" value={form.location} set={v=>setForm(f=>({...f,location:v}))}/>{!editing&&<Field label="Quantidade inicial" type="number" value={form.initial_quantity} set={v=>setForm(f=>({...f,initial_quantity:v}))}/>}<Field label="Estoque mínimo" type="number" value={form.min_stock} set={v=>setForm(f=>({...f,min_stock:v}))}/><Field label="Preço de custo" type="number" value={form.cost_price} set={v=>setForm(f=>({...f,cost_price:v}))}/><Field label="Preço de venda" type="number" value={form.sale_price} set={v=>setForm(f=>({...f,sale_price:v}))}/><Field label="NCM" value={form.ncm} set={v=>setForm(f=>({...f,ncm:v.replace(/\D/g,"").slice(0,8)}))}/></div><div className="inline-create"><Input placeholder="Nova categoria" value={categoryName} onChange={e=>setCategoryName(e.target.value)}/><Button variant="outline" onClick={addCategory}>Criar categoria</Button></div><Button onClick={saveProduct} disabled={saving}>{saving?"Salvando…":editing?"Salvar alterações":"Cadastrar produto"}</Button></div></DialogContent></Dialog>
 <Dialog open={movementOpen} onOpenChange={setMovementOpen}><DialogContent className="modal"><DialogHeader><DialogTitle>Registrar {role==="admin"?"movimentação":"saída"}</DialogTitle><DialogDescription>O saldo e o histórico serão atualizados juntos.</DialogDescription></DialogHeader><div className="modal-form"><label>Produto<select value={movement.product_id} onChange={e=>setMovement(m=>({...m,product_id:e.target.value}))}><option value="">Selecione</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} — {Number(p.quantity)} {p.unit}</option>)}</select></label><label>Tipo<select value={movement.type} disabled={role==="employee"} onChange={e=>setMovement(m=>({...m,type:e.target.value}))}><option value="entry">Entrada</option><option value="exit">Saída</option><option value="return">Devolução</option><option value="loss">Perda</option><option value="damaged">Danificado</option><option value="adjustment_in">Ajuste positivo</option><option value="adjustment_out">Ajuste negativo</option></select></label><Field label="Quantidade" type="number" value={movement.quantity} set={v=>setMovement(m=>({...m,quantity:v}))}/><Field label="Nota fiscal (opcional)" value={movement.note_number} set={v=>setMovement(m=>({...m,note_number:v}))}/><label>Motivo<textarea value={movement.reason} onChange={e=>setMovement(m=>({...m,reason:e.target.value}))} placeholder="Informe por que esta movimentação está sendo feita"/></label><Button onClick={saveMovement} disabled={saving}>{saving?"Registrando…":"Confirmar movimentação"}</Button></div></DialogContent></Dialog>
 <Dialog open={historyOpen} onOpenChange={setHistoryOpen}><DialogContent className="modal wide"><DialogHeader><DialogTitle>Histórico de estoque</DialogTitle><DialogDescription>Últimas 50 movimentações, sem possibilidade de exclusão.</DialogDescription></DialogHeader><div className="history-list">{history.length===0?<p>Nenhuma movimentação registrada.</p>:history.map(m=>{const p=products.find(x=>x.id===m.product_id);return <article key={m.id}><div><strong>{p?.name||"Produto"}</strong><span>{new Date(m.created_at).toLocaleString("pt-BR")} • {m.reason}</span></div><div><strong>{m.type==="entry"?"+":"-"}{Number(m.quantity)}</strong><span>{Number(m.previous_quantity)} → {Number(m.new_quantity)}</span></div></article>})}</div></DialogContent></Dialog></>;
}
function Mini({icon:Icon,label,value}:any){return <div><Icon/><span><small>{label}</small><strong>{value}</strong></span></div>}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label>{label}<Input type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function Detail({label,value,wide=false}:{label:string;value?:string|null;wide?:boolean}){return <div className={wide?"wide":""}><small>{label}</small><strong>{value||"Não informado"}</strong></div>}
