"use client";
import {useEffect,useState} from "react";
import {AlertTriangle,Archive,Building2,Download,Pencil,Plus,RefreshCw,Trash2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {AuthSession,Company} from "@/lib/supabase-auth";
import {downloadCsv} from "@/lib/csv";
import {getServiceOrders} from "@/lib/service-orders";
import {archiveEligible,CompanyNote,confirmClosureExport,createCompanyNote,createPlatformCompany,deleteCompanyNote,getClosures,getCompanyNotes,getInactivePlatformCompanies,getPlatformCompanies,getPlatformCompany,getSubscription,MonthlyClosure,PlatformCompany,PlatformCompanyDetail,prepareClosures,savePlatformCompany,Subscription,updateCompanyNote,updatePlatformSubscription} from "@/lib/subscriptions";
import {CrmRow,listCrm} from "@/lib/platform-crm";
const money=(v:number)=>Number(v).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const statusNames:Record<string,string>={trial:"Período de teste",active:"Ativa",past_due:"Pagamento pendente",suspended:"Suspensa",cancelled:"Cancelada",pending:"Aguardando download",exported:"Download confirmado",archived:"Arquivada"};
export function RetentionCenter({session,company}:{session:AuthSession;company:Company}){
 const[sub,setSub]=useState<Subscription>(),[rows,setRows]=useState<MonthlyClosure[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);setError("");try{await prepareClosures(session);const[s,c]=await Promise.all([getSubscription(session,company.id),getClosures(session,company.id)]);setSub(s);setRows(c)}catch(e){setError(e instanceof Error?e.message:"Não foi possível carregar os fechamentos.")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[company.id]);
 const exportMonth=async(row:MonthlyClosure)=>{setLoading(true);setError("");try{const month=row.reference_month.slice(0,7),orders=(await getServiceOrders(session,company.id,true)).filter(o=>o.status==="completed"&&o.completed_at?.slice(0,7)===month);downloadCsv(`ordens-${company.slug||"empresa"}-${month}.csv`,[["Empresa",company.name],["Mês",month],["Prazo de retenção",new Date(row.retention_until+"T12:00:00").toLocaleDateString("pt-BR")],[],["OS","Cliente","Serviço","Conclusão","Valor","Comprovante"],...orders.map(o=>[`OS-${String(o.order_number).padStart(5,"0")}`,o.customer?.name||"",o.title,o.completed_at?new Date(o.completed_at).toLocaleString("pt-BR"):"",Number(o.value).toFixed(2),o.completion_photo_path?"Disponível no sistema":"Não informado"])]);await confirmClosureExport(session,month);await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível exportar o mês.")}finally{setLoading(false)}};
 const archive=async()=>{setLoading(true);try{const n=await archiveEligible(session);await load();window.alert(`${n} ordem(ns) foram arquivadas. Nenhum produto, cliente ou movimentação foi apagado.`)}catch(e){setError(e instanceof Error?e.message:"Não foi possível arquivar.")}finally{setLoading(false)}};
 const retention=sub?.retention_days||sub?.plan?.retention_days||90;
 return <section className="panel retention-center"><div className="panel-head"><div><h3>Fechamento mensal das OS</h3><p>Os cadastros e o histórico do estoque nunca são apagados. As OS permanecem disponíveis por pelo menos {retention} dias.</p></div><div className="retention-actions"><Button variant="outline" onClick={load} disabled={loading}><RefreshCw/>Atualizar</Button><Button variant="outline" onClick={archive} disabled={loading}><Archive/>Arquivar vencidas</Button></div></div>{error&&<div className="auth-message error-message">{error}</div>}{sub&&<div className={`subscription-strip ${sub.status}`}><strong>{sub.plan?.name||sub.plan_code}</strong><span>{statusNames[sub.status]} · ciclo até {new Date(sub.current_period_end+"T12:00:00").toLocaleDateString("pt-BR")}</span></div>}<div className="table-scroll"><table><thead><tr><th>Mês</th><th>OS</th><th>Comprovantes</th><th>Valor</th><th>Prazo</th><th>Situação</th><th>Ação</th></tr></thead><tbody>{!rows.length?<tr><td colSpan={7}>{loading?"Preparando fechamentos…":"Nenhum mês anterior com OS finalizadas."}</td></tr>:rows.map(r=><tr key={r.id}><td>{new Date(r.reference_month+"T12:00:00").toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</td><td>{r.order_count}</td><td>{r.proof_count}</td><td>{money(r.total_value)}</td><td>{new Date(r.retention_until+"T12:00:00").toLocaleDateString("pt-BR")}</td><td><span className={`status ${r.status==="pending"?"warning":"success"}`}>{statusNames[r.status]}</span></td><td><Button size="sm" variant="outline" onClick={()=>exportMonth(r)} disabled={loading||r.status==="archived"}><Download/>{r.status==="pending"?"Baixar mês":"Baixar novamente"}</Button></td></tr>)}</tbody></table></div><p className="retention-note"><AlertTriangle/>O arquivamento reduz a lista operacional, mas não exclui automaticamente fotos nem registros. A limpeza de arquivos só será ativada depois de validarmos os backups.</p></section>
}
export function PlatformCompaniesView({session}:{session:AuthSession}){
 const[rows,setRows]=useState<PlatformCompany[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[showInactive,setShowInactive]=useState(false);
 const[detail,setDetail]=useState<PlatformCompanyDetail|null>(null),[editing,setEditing]=useState<PlatformCompanyDetail|null|undefined>(undefined);
 const[companyTickets,setCompanyTickets]=useState<CrmRow[]>([]),[companyTasks,setCompanyTasks]=useState<CrmRow[]>([]);
 const[companyNotes,setCompanyNotes]=useState<CompanyNote[]>([]),[noteText,setNoteText]=useState(""),[editingNote,setEditingNote]=useState<string|null>(null);
 const[form,setForm]=useState({name:"",slug:"",document:"",email:"",phone:"",address:"",planCode:"essencial",active:true});
 const load=()=>{setLoading(true);(showInactive?getInactivePlatformCompanies(session):getPlatformCompanies(session)).then(setRows).catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar as empresas.")).finally(()=>setLoading(false))};useEffect(load,[showInactive]);
 const change=async(row:PlatformCompany,status:Subscription["status"])=>{setLoading(true);setError("");try{await updatePlatformSubscription(session,{companyId:row.company_id,planCode:row.plan_name==="Profissional"?"profissional":"essencial",status,periodEnd:row.current_period_end});load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível atualizar a assinatura.");setLoading(false)}};
 const openDetail=async(row:PlatformCompany)=>{setLoading(true);setError("");try{const[d,tickets,tasks,notes]=await Promise.all([getPlatformCompany(session,row.company_id),listCrm(session,"tickets"),listCrm(session,"tasks"),getCompanyNotes(session,row.company_id)]);setDetail(d);setCompanyTickets(tickets.filter(x=>x.company_id===row.company_id));setCompanyTasks(tasks.filter(x=>x.company_id===row.company_id));setCompanyNotes(notes);setNoteText("");setEditingNote(null)}catch(e){setError(e instanceof Error?e.message:"Não foi possível abrir a empresa.")}finally{setLoading(false)}};
 const saveNote=async()=>{if(!detail||!noteText.trim())return;setLoading(true);try{if(editingNote)await updateCompanyNote(session,editingNote,noteText.trim());else await createCompanyNote(session,detail.id,noteText.trim());setCompanyNotes(await getCompanyNotes(session,detail.id));setNoteText("");setEditingNote(null)}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar a observação.")}finally{setLoading(false)}};
 const editNote=(n:CompanyNote)=>{setEditingNote(n.id);setNoteText(n.note)};
 const removeNote=async(n:CompanyNote)=>{if(!confirm("Excluir esta observação interna?"))return;setLoading(true);try{await deleteCompanyNote(session,n.id);setCompanyNotes(current=>current.filter(x=>x.id!==n.id));if(editingNote===n.id){setEditingNote(null);setNoteText("")}}catch(e){setError(e instanceof Error?e.message:"Não foi possível excluir a observação.")}finally{setLoading(false)}};
 const openNew=()=>{setForm({name:"",slug:"",document:"",email:"",phone:"",address:"",planCode:"essencial",active:true});setEditing(null)};
 const openEdit=(d:PlatformCompanyDetail)=>{setForm({name:d.name,slug:d.slug||"",document:d.document||"",email:d.email||"",phone:d.phone||"",address:d.address||"",planCode:"essencial",active:d.active});setDetail(null);setEditing(d)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError("");try{if(editing)await savePlatformCompany(session,{...editing,...form});else await createPlatformCompany(session,form);setEditing(undefined);load()}catch(err){setError(err instanceof Error?err.message:"Não foi possível salvar a empresa.");setLoading(false)}};
 const remove=async(d:PlatformCompanyDetail)=>{if(!confirm("Desativar esta empresa? Os dados, estoque e histórico serão preservados, mas o acesso ficará bloqueado."))return;setLoading(true);try{await savePlatformCompany(session,{...d,active:false});const row=rows.find(r=>r.company_id===d.id);if(row)await updatePlatformSubscription(session,{companyId:row.company_id,planCode:row.plan_name==="Profissional"?"profissional":"essencial",status:"cancelled",periodEnd:row.current_period_end});setRows(current=>current.filter(item=>item.company_id!==d.id));setDetail(null);setLoading(false)}catch(e){setError(e instanceof Error?e.message:"Não foi possível desativar a empresa.");setLoading(false)}};
 const reactivate=async(d:PlatformCompanyDetail)=>{setLoading(true);try{await savePlatformCompany(session,{...d,active:true});const row=rows.find(r=>r.company_id===d.id);if(row)await updatePlatformSubscription(session,{companyId:row.company_id,planCode:row.plan_name==="Profissional"?"profissional":"essencial",status:"active",periodEnd:new Date(Date.now()+30*86400000).toISOString().slice(0,10)});setRows(current=>current.filter(x=>x.company_id!==d.id));setDetail(null)}catch(e){setError(e instanceof Error?e.message:"Não foi possível reativar a empresa.")}finally{setLoading(false)}};
 return <><div className="page-head"><div><h2>Empresas e assinaturas</h2><p>Gerenciamento central da plataforma ER Creative.</p></div><div className="actions"><Button variant="outline" onClick={()=>setShowInactive(x=>!x)}>{showInactive?"Ver ativas":"Ver desativadas"}</Button><Button variant="outline" onClick={load} disabled={loading}><RefreshCw/>Atualizar</Button>{!showInactive&&<Button onClick={openNew}><Plus/>Nova empresa</Button>}</div></div>{error&&<div className="auth-message error-message">{error}{error.includes("platform_list_inactive")&&" Execute a SQL 018 no Supabase."}</div>}<section className="panel table-panel"><div className="employee-summary"><span><strong>{rows.length}</strong> {showInactive?"desativadas":"empresas"}</span><span><strong>{rows.filter(r=>r.subscription_status==="active").length}</strong> assinaturas ativas</span><span><strong>{rows.reduce((n,r)=>n+Number(r.employee_count),0)}</strong> usuários</span></div><div className="table-scroll"><table><thead><tr><th>Empresa</th><th>Plano</th><th>Usuários</th><th>OS</th><th>Ciclo</th><th>Situação</th></tr></thead><tbody>{!rows.length?<tr><td colSpan={6}>{loading?"Carregando empresas…":showInactive?"Nenhuma empresa desativada.":"Nenhuma empresa encontrada."}</td></tr>:rows.map(r=><tr key={r.company_id} className="clickable-row" onClick={()=>openDetail(r)}><td><div className="product"><div className="square"><Building2/></div><span><strong>{r.company_name}</strong><small>{r.slug||"Sem identificador"}</small></span></div></td><td>{r.plan_name}<small className="table-sub">{r.retention_days} dias de retenção</small></td><td>{r.employee_count}</td><td>{r.order_count}</td><td>{new Date(r.current_period_end+"T12:00:00").toLocaleDateString("pt-BR")}</td><td onClick={e=>e.stopPropagation()}>{showInactive?<span className="status danger-bg">Desativada</span>:<select value={r.subscription_status} onChange={e=>change(r,e.target.value as Subscription["status"])} disabled={loading}><option value="trial">Teste</option><option value="active">Ativa</option><option value="past_due">Pendente</option><option value="suspended">Suspensa</option><option value="cancelled">Cancelada</option></select>}</td></tr>)}</tbody></table></div></section>
 <Dialog open={!!detail} onOpenChange={o=>!o&&setDetail(null)}><DialogContent className="company-detail-dialog"><DialogHeader><DialogTitle>Informações da empresa</DialogTitle><DialogDescription>Cadastro, suporte, tarefas e observações internas.</DialogDescription></DialogHeader>{detail&&<><div className="company-detail-scroll"><div className="detail-grid">{[["Empresa",detail.name],["Identificador",detail.slug],["CNPJ/CPF",detail.document],["E-mail",detail.email],["Telefone",detail.phone],["Endereço",detail.address],["Situação",detail.active?"Ativa":"Desativada"],["Cadastro",new Date(detail.created_at).toLocaleDateString("pt-BR")]].map(x=><div key={x[0]}><small>{x[0]}</small><strong>{x[1]||"Não informado"}</strong></div>)}</div><div className="company-relations"><section><h4>Chamados ({companyTickets.length})</h4>{companyTickets.length?companyTickets.slice(0,5).map(x=><div key={x.id}><strong>{x.title}</strong><span>{x.status==="open"?"Aberto":x.status==="in_progress"?"Em atendimento":x.status==="resolved"?"Resolvido":x.status}</span></div>):<p>Nenhum chamado vinculado.</p>}</section><section><h4>Tarefas ({companyTasks.length})</h4>{companyTasks.length?companyTasks.slice(0,5).map(x=><div key={x.id}><strong>{x.title}</strong><span>{x.status==="pending"?"Pendente":x.status==="in_progress"?"Em andamento":x.status==="completed"?"Concluída":x.status}</span></div>):<p>Nenhuma tarefa vinculada.</p>}</section></div><section className="company-notes"><h4>Observações internas</h4><div className="note-editor"><textarea rows={3} placeholder="Escreva uma informação importante sobre esta empresa…" value={noteText} onChange={e=>setNoteText(e.target.value)}/><div>{editingNote&&<Button size="sm" variant="outline" onClick={()=>{setEditingNote(null);setNoteText("")}}>Cancelar</Button>}<Button size="sm" onClick={saveNote} disabled={loading||!noteText.trim()}>{editingNote?"Salvar alteração":"Adicionar observação"}</Button></div></div>{companyNotes.length?<div className="note-list">{companyNotes.map(n=><article key={n.id}><button className="note-content" onClick={()=>editNote(n)}><strong>{n.note}</strong><small>{new Date(n.created_at).toLocaleString("pt-BR")}</small></button><div><Button size="icon" variant="ghost" title="Editar observação" onClick={()=>editNote(n)}><Pencil/></Button><Button size="icon" variant="ghost" title="Excluir observação" onClick={()=>removeNote(n)}><Trash2/></Button></div></article>)}</div>:<p className="empty-note">Nenhuma observação interna cadastrada.</p>}</section></div><div className="dialog-actions"><Button variant="outline" onClick={()=>openEdit(detail)}><Pencil/>Editar empresa</Button><Button variant="destructive" onClick={()=>remove(detail)}><Trash2/>Desativar</Button></div></>}</DialogContent></Dialog>
 <Dialog open={editing!==undefined} onOpenChange={o=>!o&&setEditing(undefined)}><DialogContent><DialogHeader><DialogTitle>{editing?"Editar empresa":"Cadastrar empresa"}</DialogTitle><DialogDescription>Os dados poderão ser alterados depois.</DialogDescription></DialogHeader><form onSubmit={save} className="form-grid"><label>Nome<Input required value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></label><label>Identificador do link<Input required value={form.slug} onChange={e=>setForm(f=>({...f,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,"-")}))}/></label><label>CNPJ/CPF<Input value={form.document} onChange={e=>setForm(f=>({...f,document:e.target.value}))}/></label><label>E-mail<Input type="email" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/></label><label>Telefone<Input value={form.phone} onChange={e=>setForm(f=>({...f,phone:e.target.value}))}/></label>{!editing&&<label>Plano<select value={form.planCode} onChange={e=>setForm(f=>({...f,planCode:e.target.value}))}><option value="essencial">Essencial</option><option value="profissional">Profissional</option></select></label>}<label className="span-2">Endereço<Input value={form.address} onChange={e=>setForm(f=>({...f,address:e.target.value}))}/></label>{editing&&<label className="check span-2"><input type="checkbox" checked={form.active} onChange={e=>setForm(f=>({...f,active:e.target.checked}))}/>Empresa ativa</label>}<div className="dialog-actions span-2"><Button type="button" variant="outline" onClick={()=>setEditing(undefined)}>Cancelar</Button><Button type="submit" disabled={loading}>Salvar</Button></div></form></DialogContent></Dialog></>
}
