import { AuthSession, SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from "./supabase-auth";

export type ContactType="customer"|"supplier";
export type BusinessContact={id:string;company_id:string;entity_type:ContactType;person_type:"person"|"company";name:string;trade_name:string|null;document:string|null;contact_name:string|null;phone:string|null;email:string|null;postal_code:string|null;address:string|null;address_number:string|null;complement:string|null;neighborhood:string|null;city:string|null;state:string|null;notes:string|null;active:boolean;created_at:string;updated_at:string};
export type ContactInput=Omit<BusinessContact,"id"|"active"|"created_at"|"updated_at">;
const headers=(session:AuthSession)=>({apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"});
async function errorOf(response:Response){const body:any=await response.json().catch(()=>({}));return body?.message||body?.error||body?.hint||"Não foi possível concluir a operação."}
export async function getBusinessContacts(session:AuthSession,companyId:string,type:ContactType):Promise<BusinessContact[]>{const response=await fetch(`${SUPABASE_URL}/rest/v1/business_contacts?company_id=eq.${companyId}&entity_type=eq.${type}&active=eq.true&select=*&order=name.asc`,{headers:headers(session)});if(!response.ok)throw new Error(await errorOf(response));return response.json()}
export async function createBusinessContact(session:AuthSession,input:ContactInput):Promise<BusinessContact>{const response=await fetch(`${SUPABASE_URL}/rest/v1/business_contacts`,{method:"POST",headers:{...headers(session),Prefer:"return=representation"},body:JSON.stringify(input)});if(!response.ok)throw new Error(await errorOf(response));const rows=await response.json() as BusinessContact[];return rows[0]}
export async function updateBusinessContact(session:AuthSession,id:string,input:Partial<ContactInput>&{active?:boolean}):Promise<BusinessContact>{const response=await fetch(`${SUPABASE_URL}/rest/v1/business_contacts?id=eq.${id}`,{method:"PATCH",headers:{...headers(session),Prefer:"return=representation"},body:JSON.stringify({...input,updated_at:new Date().toISOString()})});if(!response.ok)throw new Error(await errorOf(response));const rows=await response.json() as BusinessContact[];const row=rows[0];if(!row)throw new Error("Cadastro não encontrado ou sem permissão.");return row}
