import {AuthSession,SUPABASE_PUBLISHABLE_KEY,SUPABASE_URL} from "./supabase-auth";
const headers=(s:AuthSession)=>({apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${s.access_token}`,"Content-Type":"application/json"});
async function errorOf(r:Response){const b:any=await r.json().catch(()=>({}));return b?.message||b?.error||"Não foi possível concluir a operação."}
export type Subscription={company_id:string;plan_code:string;status:"trial"|"active"|"past_due"|"suspended"|"cancelled";current_period_end:string;grace_until:string|null;retention_days:number|null;plan?:{name:string;retention_days:number;monthly_price:number}|null};
export type MonthlyClosure={id:string;reference_month:string;status:"pending"|"exported"|"archived";order_count:number;proof_count:number;total_value:number;retention_until:string;exported_at:string|null};
export type PlatformCompany={company_id:string;company_name:string;slug:string|null;plan_name:string;subscription_status:Subscription["status"];current_period_end:string;retention_days:number;employee_count:number;order_count:number};
export async function getSubscription(s:AuthSession,companyId:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/company_subscriptions?company_id=eq.${companyId}&select=*,plan:subscription_plans(name,retention_days,monthly_price)&limit=1`,{headers:headers(s)});if(!r.ok)throw new Error(await errorOf(r));const rows=await r.json();return rows[0] as Subscription|undefined}
export async function prepareClosures(s:AuthSession){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/prepare_monthly_os_closures`,{method:"POST",headers:headers(s),body:"{}"});if(!r.ok)throw new Error(await errorOf(r));return r.json()}
export async function getClosures(s:AuthSession,companyId:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/monthly_os_closures?company_id=eq.${companyId}&select=*&order=reference_month.desc`,{headers:headers(s)});if(!r.ok)throw new Error(await errorOf(r));return r.json() as Promise<MonthlyClosure[]>}
export async function confirmClosureExport(s:AuthSession,month:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/confirm_monthly_os_export`,{method:"POST",headers:headers(s),body:JSON.stringify({p_reference_month:`${month.slice(0,7)}-01`})});if(!r.ok)throw new Error(await errorOf(r))}
export async function archiveEligible(s:AuthSession){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/archive_eligible_os`,{method:"POST",headers:headers(s),body:"{}"});if(!r.ok)throw new Error(await errorOf(r));return Number(await r.json())}
export async function getPlatformCompanies(s:AuthSession){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/platform_list_companies`,{method:"POST",headers:headers(s),body:"{}"});if(!r.ok)throw new Error(await errorOf(r));return r.json() as Promise<PlatformCompany[]>}
export async function getInactivePlatformCompanies(s:AuthSession){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/platform_list_inactive_companies`,{method:"POST",headers:headers(s),body:"{}"});if(!r.ok)throw new Error(await errorOf(r));return r.json() as Promise<PlatformCompany[]>}
export async function updatePlatformSubscription(s:AuthSession,data:{companyId:string;planCode:string;status:Subscription["status"];periodEnd:string}){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/platform_update_subscription`,{method:"POST",headers:headers(s),body:JSON.stringify({p_company_id:data.companyId,p_plan_code:data.planCode,p_status:data.status,p_period_end:data.periodEnd})});if(!r.ok)throw new Error(await errorOf(r))}
export type PlatformCompanyDetail={id:string;name:string;slug:string|null;document:string|null;email:string|null;phone:string|null;address:string|null;active:boolean;created_at:string};
export async function getPlatformCompany(s:AuthSession,id:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/platform_get_company`,{method:"POST",headers:headers(s),body:JSON.stringify({p_company_id:id})});if(!r.ok)throw new Error(await errorOf(r));return r.json() as Promise<PlatformCompanyDetail>}
export async function createPlatformCompany(s:AuthSession,data:{name:string;slug:string;document:string;email:string;phone:string;address:string;planCode:string}){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/platform_create_company`,{method:"POST",headers:headers(s),body:JSON.stringify({p_name:data.name,p_slug:data.slug,p_document:data.document,p_email:data.email,p_phone:data.phone,p_address:data.address,p_plan_code:data.planCode})});if(!r.ok)throw new Error(await errorOf(r));return r.json() as Promise<string>}
export async function savePlatformCompany(s:AuthSession,data:PlatformCompanyDetail){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/platform_update_company`,{method:"POST",headers:headers(s),body:JSON.stringify({p_company_id:data.id,p_name:data.name,p_slug:data.slug||"",p_document:data.document||"",p_email:data.email||"",p_phone:data.phone||"",p_address:data.address||"",p_active:data.active})});if(!r.ok)throw new Error(await errorOf(r))}
export type CompanyNote={id:string;company_id:string;note:string;created_at:string};
export async function getCompanyNotes(s:AuthSession,companyId:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/company_notes?company_id=eq.${companyId}&deleted_at=is.null&select=*&order=created_at.desc`,{headers:headers(s)});if(!r.ok)throw new Error(await errorOf(r));return r.json() as Promise<CompanyNote[]>}
export async function createCompanyNote(s:AuthSession,companyId:string,note:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/company_notes`,{method:"POST",headers:{...headers(s),Prefer:"return=representation"},body:JSON.stringify({company_id:companyId,note,created_by:s.user.id})});if(!r.ok)throw new Error(await errorOf(r));return (await r.json())[0] as CompanyNote}
export async function updateCompanyNote(s:AuthSession,id:string,note:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/company_notes?id=eq.${id}`,{method:"PATCH",headers:{...headers(s),Prefer:"return=representation"},body:JSON.stringify({note})});if(!r.ok)throw new Error(await errorOf(r));return (await r.json())[0] as CompanyNote}
export async function deleteCompanyNote(s:AuthSession,id:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/company_notes?id=eq.${id}`,{method:"PATCH",headers:headers(s),body:JSON.stringify({deleted_at:new Date().toISOString()})});if(!r.ok)throw new Error(await errorOf(r))}
export type PlatformPayment={id:string;company_id:string;reference_month:string;amount:number;due_date:string;paid_at:string|null;status:"pending"|"paid"|"overdue"|"cancelled";notes:string|null;created_at:string};
export async function getPlatformPayments(s:AuthSession){const r=await fetch(`${SUPABASE_URL}/rest/v1/platform_payments?deleted_at=is.null&select=*&order=due_date.desc`,{headers:headers(s)});if(!r.ok)throw new Error(await errorOf(r));return r.json() as Promise<PlatformPayment[]>}
export async function createPlatformPayment(s:AuthSession,data:Omit<PlatformPayment,"id"|"created_at"|"paid_at">){const r=await fetch(`${SUPABASE_URL}/rest/v1/platform_payments`,{method:"POST",headers:{...headers(s),Prefer:"return=representation"},body:JSON.stringify(data)});if(!r.ok)throw new Error(await errorOf(r));return (await r.json())[0] as PlatformPayment}
export async function updatePlatformPayment(s:AuthSession,id:string,data:Partial<PlatformPayment>){const r=await fetch(`${SUPABASE_URL}/rest/v1/platform_payments?id=eq.${id}`,{method:"PATCH",headers:{...headers(s),Prefer:"return=representation"},body:JSON.stringify({...data,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await errorOf(r));return (await r.json())[0] as PlatformPayment}
export async function deletePlatformPayment(s:AuthSession,id:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/platform_payments?id=eq.${id}`,{method:"PATCH",headers:headers(s),body:JSON.stringify({deleted_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(await errorOf(r))}
